web:
  image: nginx:alpine
  volumes:
    - './config/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
  volumes_from:
    - app
  ports:
    - '80:80'
  links:
    - app
    - node-socketio

app:
  image: donysukardi/erpnext:stable
  links:
    - db
    - redis-socketio
    - redis-cache
    - redis-queue

scheduler:
  image: donysukardi/erpnext:stable
  command: scheduler
  links:
    - db
    - redis-socketio
    - redis-cache
    - redis-queue

worker-default:
  image: donysukardi/erpnext:stable
  command: worker-default
  links:
    - db
    - redis-socketio
    - redis-cache
    - redis-queue

worker-long:
  image: donysukardi/erpnext:stable
  command: worker-long
  links:
    - db
    - redis-socketio
    - redis-cache
    - redis-queue

worker-short:
  image: donysukardi/erpnext:stable
  command: worker-short
  links:
    - db
    - redis-socketio
    - redis-cache
    - redis-queue

redis-cache:
  image: redis

redis-queue:
  image: redis

redis-socketio:
  image: redis

node-socketio:
  image: donysukardi/erpnext:stable
  command: node-socketio
  links:
    - db
    - redis-socketio
    - redis-cache
    - redis-queue

db:
  image: mariadb:latest
  volumes:
    - './config/my.cnf:/etc/mysql/conf.d/frappe.cnf'
  environment:
    - MYSQL_ROOT_PASSWORD=asdfasdfasdf
    - MYSQL_USER=frappe
    - MYSQL_PASSWORD=frappe
    - MYSQL_DATABASE=frappe
